name: tests

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: cd src && chmod +x install.sh && ./install.sh
    - name: make
      run: cd src && make
    - name: test
      run: cd src && make test
